name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download hadesmem release
      run: |
        Invoke-WebRequest https://github.com/namreeb/hadesmem/releases/download/v1.7.0/hadesmem-v142-Release-Win32.zip -OutFile hadesmem.zip
        Expand-Archive -Path hadesmem.zip -DestinationPath .

    - name: Build Boost
      run: |
        Invoke-WebRequest https://boostorg.jfrog.io/artifactory/main/release/1.78.0/source/boost_1_78_0.zip -OutFile boost.zip
        Expand-Archive -Path boost.zip -DestinationPath .
        cd boost_1_78_0
        .\bootstrap
        .\b2 --with-filesystem --with-program_options link=static threading=multi runtime-link=shared architecture=x86 address-model=32 stage

    - name: Configure CMake
      run: cmake -A Win32 -B ${{github.workspace}}/build -DBOOST_ROOT=boost_1_78_0 -DHADESMEM_ROOT=hadesmem-v142-Release-Win32 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/nampower

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        cmake --install ${{github.workspace}}/build

    - name: Publish artifact
      uses: actions/upload-artifact@v3
      with:	
        name: nampower-2.2
        path: ${{ github.workspace }}/nampower/*

    - name: Setup release
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        $ref_name = "2.2"
        move nampower nampower-${ref_name}
        Compress-Archive nampower-${ref_name} nampower-${ref_name}.zip

    - uses: softprops/action-gh-release@v1
      name: Upload assets to release
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: nampower-2.2.zip
        fail_on_unmatched_files: true